spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user_activity_log
      username: myUser
      password: myPassword
  threads:
    virtual:
      enabled: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
      apache:
        http: DEBUG
        http.wire: DEBUG
